version: '3.8'

services:
  backend:
    build: ./backend-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend-app:/app
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://user:password@db:5432/plc_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - plc-network

  db:
    image: postgres:14-alpine
    container_name: plc-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=plc_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - plc-network

volumes:
  db_data:

networks:
  plc-network:
    driver: bridge